change:
  debug: False


prolog:

  traindir: Null
  evaldir: Null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  steps: e7
  eval_every: 500
  log_every: 10
  reset_every: 0
  gpu_growth: True
  precision: 32
  debug: False
  expl_gifs: False

  # Environment
  task: 'prolog_void'
  envs: 1
  action_repeat: 1
  time_limit: 1000
  prefill: 200000
  eval_noise: 0.0
  clip_rewards: 'identity'
  atari_grayscale: False

  # Model
  dyn_cell: 'gru'
  dyn_hidden: 100
  dyn_deter: 100
  dyn_stoch: 20
  dyn_discrete: 32
  dyn_input_layers: 4
  dyn_output_layers: 4
  dyn_shared: False
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['image', 'reward', 'discount', 'action_mask']
  units: 200
  reward_layers: 1
  discount_layers: 1
  value_layers: 3
  actor_layers: 4
  act: 'elu'
  value_head: 'normal'
  kl_scale: '1.0'
  kl_balance: '0.8'
  kl_free: '0.5'
  pred_discount: True
  discount_scale: 1.0
  reward_scale: 1.0
  weight_decay: 0.0

  #GNN
  gnn_start_shape: [4,1,4]
  gnn_next_shape: [32,64,32]
  gnn_layers: 10
  gnn_hidden_val: 200
  gnn_hidden_act: 64

  # Training
  #....batch_size: 50
  #....batch_length: 1
  train_every: 25
  train_steps: 10
  pretrain: 5
  model_lr: 0.0003
  value_lr: 0.001
  actor_lr: 0.001
  opt_eps: 0.0008
  grad_clip: 100
  value_grad_clip: 100
  actor_grad_clip: 100
  dataset_size: 200000
  oversample_ends: False
  slow_value_target: False
  slow_actor_target: False
  slow_target_update: 100
  slow_target_fraction: 1
  opt: 'adam' 

  # Behavior.
  discount: 0.66
  discount_lambda: 0.8
  imag_horizon: 3
  imag_gradient: 'reinforce'
  imag_gradient_mix: '0.1'
  imag_sample: True
  actor_dist: 'normal'
  actor_entropy: '1e-4'
  actor_state_entropy: 0.0
  actor_init_std: 1.0
  actor_min_std: 0.1
  actor_disc: 5
  actor_temp: 0.1
  actor_outscale: 0.0
  expl_amount: 0.0
  eval_state_mean: False
  collect_dyn_sample: True
  behavior_stop_grad: True
  value_decay: 0.0
  future_entropy: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 10000000.0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'embed'
  disag_log: True
  disag_models: 3
  disag_offset: 0
  disag_layers: 1
  disag_units: 200